# Generated by Django 3.2.13 on 2022-09-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
